# Generated by Django 5.0.6 on 2024-05-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_class_field_studymaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='class_field',
        ),
        migrations.DeleteModel(
            name='StudyMaterial',
        ),
    ]
