# Generated by Django 5.0.6 on 2024-06-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='subject',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
