# Generated by Django 5.0.6 on 2024-06-11 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_studymaterial_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='uploaded_by',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
