# Generated by Django 5.0.6 on 2024-06-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_subject_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attendance',
            new_name='dailyattendance',
        ),
    ]
