# Generated by Django 5.0.6 on 2024-06-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_attendance_dailyattendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dailyattendance',
            new_name='attendance',
        ),
    ]
