# Generated by Django 5.0.6 on 2024-06-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_classsubject_classattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classattendance',
            options={'verbose_name': 'Class Attendance', 'verbose_name_plural': 'Class Attendances'},
        ),
    ]
