# Generated by Django 5.0.6 on 2024-06-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_classattendance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PRINCIPAL', 'Principal'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('WAITING', 'Waiting')], default='WAITING', max_length=50),
        ),
    ]
